version: '3'
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
